In [1]:
import pandas as pd

In [2]:
tut_dictionory = {'name': ['basic machinelearning', 'deep learning', 'efficient python programming'],
'price': ['120.0', '300.0', None],
'level': [0, 1, 2]}
df = pd.DataFrame(tut_dictionory)
df.head()

name  price  level
0         basic machinelearning  120.0      0
1                 deep learning  300.0      1
2  efficient python programming   None      2

In [3]:
df.dropna(inplace=False)

name  price  level
0  basic machinelearning  120.0      0
1          deep learning  300.0      1

In [4]:
df

name  price  level
0         basic machinelearning  120.0      0
1                 deep learning  300.0      1
2  efficient python programming   None      2

In [5]:
import numpy as np

In [6]:
a = np.array([2,3,4,5])

In [7]:
a.append(0)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [8]:
a[0] = 1

In [9]:
a

array([1, 3, 4, 5])

In [10]:
a.flags.writeable = False

In [11]:
a[0] = 2

ValueError: assignment destination is read-only

In [12]:
b = a.copy()

In [13]:
b[0] = 2

In [14]:
b

array([2, 3, 4, 5])

In [15]:
s = "hello"

In [18]:
s += s + " world"

In [19]:
s

'hellohelloworldhellohelloworld world'

In [20]:
def add(a,b):
    return a + b
def subtract(x,y):
    return add(x,y *-1)

In [21]:
assert subtract(3,2) == 1

In [22]:
items = [1, 2, 3, 4, 5]
squared = list(map(lambda x: x**2, items))

In [23]:
squared

[1, 4, 9, 16, 25]

In [24]:
items = np.array([1,2,3,4,5])
items**2

array([ 1,  4,  9, 16, 25])

In [25]:
number_list = range(-5, 5)
less_than_zero = list(filter(lambda x: x < 0, number_list))
print(less_than_zero)

[-5, -4, -3, -2, -1]


In [26]:
number_list_arr = np.array(range(-5,5))

In [28]:
number_list_arr[number_list_arr>0]

array([1, 2, 3, 4])

In [30]:
A = [[1,-1,2],[0,3,1]]
x = [2,1,0]
result = []
row_count = 0
for row in A:
    partial_result = 0
    for i in range(len(row)):
        a_elem = row[i]
        x_elem = x[i]
        partial_result += (a_elem * x_elem)
    result.append(partial_result)
    row_count += 1
    
result

[1, 3]

In [32]:
A_arr = np.array([[1,-1,2],[0,3,1]])
x_arr = np.array([2,1,0])
A_arr @ x_arr

array([1, 3])

seaborn 是一个用于在 Python 中制作统计图形的库。建立在 matplotlib 之上，并与 pandas 数据结构紧密结合。

seaborn 帮助你探索和理解你的数据。绘图函数在包含整个数据集的数据框和数组上操作，并在内部进行必要的语义映射和统计聚合，以产生信息丰富的图表。面向数据集的声明式 API 让你专注于不同数据集的内容。